### ISSUE TITLE
Return Degree of Similarity Coefficient or Modify Similarity Criteria

### ISSUE THREAD

**Issue by mike-lloyd03** [vitali-fedulov/images#6]
Thanks for writing this tool. I'm working on comparing duplicates between two large libraries and this is a life saver. 

Is it possible have the `Similar` function return the degree of similarity between two images? Or perhaps allow the user to define the criteria for a similar image?

I have multiple images that indeed are very similar (taken at similar time in same environment of same subject) which this algorithm correctly identifies as similar. I'd like to be able to see a value for how similar the two images are so I can quickly determine if I should keep it or not. 

Can I override the `euclCoeff` value to achieve this?

**Comment by vitali-fedulov** [comment]
Great feedback, Mike

I will be looking at your request during next days.

(0)    Just for info I am also preparing a considerably reworked backward-incompatible new version of _images_ (as a separate package _images3_), which makes use of **proper hashes** for much faster search. It will still have a function like `Similar`.

Meanwhile, some ideas for quick fixes on your proposals. Please let me know if this makes sense.

(1)    euclCoeff is unexported now, I could make all the constants exported, thus possible to override the values by simple reassignment. 

(2)    Or I could introduce a func `SimilarCustom` with a similar signature to `Similar`, except with similarity coefficients as arguments. Also this function could return 4 values, instead of _bool_ only. Those would be: bool (similar or not), filter 2a value, filter 2b value, filter 3 value.
 
(3)    The filter values are the sum variables for each filter. Thus, when you need, you can treat the sum values as a degree of similarity and ignore the bool verdict. Note, that having 3 values means you might need to create a combined similarity degree values with some kind of weights or other ranking mechanism, but this up to you as a package user. The plus of the approach is that you may find a better metric of similarity than thresholds I use in `Similar`.
 
(4)    I propose to exclude filter 1 values in the return of `SimilarCustom`, as not sure we need to go that deep. But it is possible to add the values too, this is simple.

(5)   By the way, just for info, I am also working on a search engine somewhat similar to yours [dedugo](https://github.com/mike-lloyd03/dedugo). Just wondering (for myself for now) of how much can be reused or be done with a joint effort. Let me know how best to provide feedback on your project. Do you need feedback? Or it is an urgent project, not indented for longer term support and wider usage.

I am happy you find the package useful.

**Comment by mike-lloyd03** [comment]
Yes I think something along the lines of your `SimilarCustom` proposal would work nicely. Then the user can tweak the settings to find something suitable for his use case.

Regarding dedugo, I'd love to team up. I've only been working with Go for a few months so I'm sure my code could use a lot of improvement. But it's working okay for now. I was able to load up about 4000 images and compare them in just over 2 minutes. But it would be cool to get a really fast duplicate image finder working for the community.

The `Similar` function is actually the fastest part of the process. Comparing each of 2000 pictures with 2000 other pictures (a total of 4 million calls to `Similar`) only took about 5-10 seconds. It's the opening and hashing part that takes the longest. I look forward to implementing your improvements on v3.

**Comment by G2G2G2G** [comment]
I like the SimilarCustom idea as well
Nice projects with the dedugo and joint effort.
(here's a similar c++ one I've used for years, maybe it has some ideas for dedugo https://github.com/neatdecisions/detwinner )

**Comment by vitali-fedulov** [comment]
Hi Mike,

I have Added `SimilarCustom`. It returns 4 metric values:
delta, euc, eucNorm, corr := SimilarCustom(hA, hB, sizeA, sizeB)
The function does not return the similarity verdict.

Please let me know, if/when you test it. I am very curious how useful the function is.
